eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 9004

spring:
  application:
    name: client-config
  cloud:
    config:
      uri: http://localhost:8888/
      name: config-client
      profile: dev
