server:
  port: 9001

spring:
  application:
    name: eureka-provider

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/  #,http://localhost:9010/eureka/,http://localhost:9011/eureka/,http://localhost:9012/eureka/
  instance:
    prefer-ip-address: true