spring:
  application:
    name: zuul-service-filter

server:
  port: 9013


zuul:
  routes:
    api:
      path: /**
      serviceId: eureka-provider


eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/